---
abstract: 'This Module makes a text vertically.'
author:
  - 'Kazuhiro Homma <kazuph@cpan.org>'
build_requires:
  Test::Base::Less: 0.09
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Tategaki
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Acme::Tategaki:
    file: lib/Acme/Tategaki.pm
    version: 0.12
requires:
  Array::Transpose::Ragged: 0
  Encode::Locale: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/kazuph/Acme-Tategaki/issues
  homepage: https://github.com/kazuph/Acme-Tategaki
  repository: git://github.com/kazuph/Acme-Tategaki.git
version: 0.12
x_contributors:
  - 'Ryo Okamoto <ryo@aquahill.net>'
  - 'Kazuhiro Homma <kazu.homma@gmail.com>'
